#!/usr/bin/env python3
"""
migrate_report.py
=================
One-time migration: rewrites all historical Position Monitor "Funds State"
sections and ensures reverse-chronological block ordering in the HTML report.

Two categories of changes applied to each day block:

  1. Label rewrites in the Funds State card:
       Old: <b>Sold</b>: $X proceeds &nbsp;(±$Y gain/loss inline)
       New: <b>Sold proceeds</b>: $X  (own line)
             <b>Realised P&L</b>:  ±$Y  (own line, ±-prefixed)

       Injects "Total funds available" and "Total gain/loss" lines where
       absent.  Historical values cannot include unrealised open-position
       market values (that data was not stored), so the injected lines are
       annotated "(historical, open positions excluded)".

  2. Reverse-chronological ordering:
       Reports generated before the MONITOR_SECTION_TOP anchor was introduced
       appended new day blocks chronologically (oldest first).  Migration
       reverses block order and plants the anchor so future daily runs
       continue to prepend correctly.

Usage
-----
    python migrate_report.py                      # default report path
    python migrate_report.py path/to/report.html  # explicit path
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import List, Tuple

# ── HTML fragments that identify structural boundaries ──────────────────────

# <table> spacer with height=8, generated by _spacer(8) in report_html.py
_SPACER8 = (
    "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
    "<tr><td height='8' style='font-size:1px;line-height:1px'>&nbsp;</td></tr>"
    "</table>"
)

# Start of the dark header banner (Position Monitor and Pipeline both use this)
_DARK_HDR_START = (
    "<table width='100%' cellpadding='0' cellspacing='0' border='0'"
    " bgcolor='#1a1d2e'"
)

# Position Monitor day block boundary = spacer immediately before dark header
_BLOCK_BOUNDARY = _SPACER8 + _DARK_HDR_START

# Section markers used by append_positions_report / _write_position_report
_SECTION_ANCHOR = "<!-- MONITOR_SECTION_TOP -->"
_DAY_END = "<!-- MONITOR_DAY_END -->"
_PLACEHOLDER = "<!-- POSITION_MONITOR_PLACEHOLDER -->"

# Text unique to Position Monitor headers (vs. Pipeline report)
_POSMONI_TITLE = "&#128202; Position Monitor"

# Exact doc_close string produced by report_html._doc_close()
_DOC_CLOSE = (
    "\n</td></tr></table>\n</td></tr></table>\n</body>\n</html>"
)

# Opening of the Funds State <div> block (unchanged across all versions)
_FUNDS_DIV_OPEN = (
    "<div style='margin:16px 0;padding:14px 16px;border:1px solid #dde1ea;"
    "background:#ffffff;font-family:Arial,Helvetica,sans-serif;color:#1a1d2e'>"
    "<div style='font-size:13px;font-weight:bold;margin-bottom:8px;'>Funds State</div>"
)

# ── regex patterns ──────────────────────────────────────────────────────────

# Date embedded in the Position Monitor subtitle (YYYYMMDD format)
_DATE_RE = re.compile(r"Daily Report &nbsp;&middot;&nbsp; (\d{8})")

# Old "Sold: $X proceeds (±$Y gain/loss)" label — introduced in 20e8791,
# replaced in 2b9b4da.
_OLD_SOLD_RE = re.compile(
    r"<li><b>Sold</b>: \$([\d,]+\.\d{2}) proceeds &nbsp;\("
    r"<span style='color:(#[0-9a-f]+);font-weight:bold'>"
    r"(\+?\$-?[\d,]+\.\d{2}) (gain|loss)</span>\)</li>"
)

# Cash amounts that appear in the Funds State list
_FUNDS_AFTER_RE = re.compile(
    r"<li><b>Funds after sells</b>: \$([\d,]+\.\d{2})</li>"
)
_FUNDS_REMAINING_RE = re.compile(
    r"<li><b>Funds remaining</b>: \$([\d,]+\.\d{2})</li>"
)

# Realised P&L line — new format (after step 1 transform has already run)
_REALISED_PNL_RE = re.compile(
    r"<li><b>Realised P&L</b>: "
    r"<span style='color:(#[0-9a-f]+);font-weight:bold'>([+-]\$[\d,]+\.\d{2})</span></li>"
)

# doc_close fragments that may be embedded mid-file by the old appending logic
_DOC_FRAGMENT_RE = re.compile(
    r"(?:\n</td></tr></table>){1,2}\s*(?:</body>\s*</html>)?\s*$"
    r"|</body>\s*</html>\s*$",
)


# ── helpers ─────────────────────────────────────────────────────────────────

def _normalize_pnl(raw: str, word: str) -> str:
    """
    Convert old P&L token to the new ±$X.XX format used by _fmt_pnl().

    Old positive: '+$150.00'  (pnl_sign='+', realized_pnl=150.00)
    Old negative: '$-150.00'  (pnl_sign='',  realized_pnl=-150.00)
    New positive: '+$150.00'
    New negative: '-$150.00'
    """
    if word == "loss":
        # '$-150.00' → '-$150.00'
        amount = raw[1:]          # strip leading '$' → '-150.00'
        return "-$" + amount[1:]  # move minus before '$' → '-$150.00'
    # 'gain' case: raw is '+$150.00' or '$0.00' (defensive)
    return raw if raw.startswith("+") else ("+" + raw)


def _strip_doc_close(block: str) -> str:
    """Remove any doc_close or partial doc_close fragments from the block tail."""
    return _DOC_FRAGMENT_RE.sub("", block).rstrip()


def _get_block_date(block: str) -> str:
    """Return the YYYYMMDD date string embedded in a Position Monitor block."""
    m = _DATE_RE.search(block)
    return m.group(1) if m else ""


# ── per-block transformations ────────────────────────────────────────────────

def _apply_sold_label_fix(funds_div: str) -> str:
    """
    Replace the old inline 'Sold: $X proceeds (±$Y gain/loss)' pattern with
    two separate lines: 'Sold proceeds: $X' and 'Realised P&L: ±$Y'.
    """
    def _repl(m: re.Match) -> str:
        proceeds = m.group(1)  # e.g. '1,234.56'
        color = m.group(2)     # e.g. '#0a7c4e'
        raw_pnl = m.group(3)   # e.g. '+$150.00' or '$-150.00'
        word = m.group(4)      # 'gain' or 'loss'
        pnl_fmt = _normalize_pnl(raw_pnl, word)
        return (
            f"<li><b>Sold proceeds</b>: ${proceeds}</li>"
            f"<li><b>Realised P&L</b>: "
            f"<span style='color:{color};font-weight:bold'>{pnl_fmt}</span></li>"
        )

    return _OLD_SOLD_RE.sub(_repl, funds_div)


def _inject_totals_if_missing(funds_div: str) -> str:
    """
    Add 'Total funds available' and 'Total gain/loss' lines before </ul></div>
    when they are absent (i.e. the block was generated by the old code).

    Historical values are approximations:
      - Total funds available  = cash after sells (no unrealised position value)
      - Total gain/loss        = realised P&L only (no unrealised P&L)
    Both lines carry a note flagging this limitation.
    """
    if "Total funds available" in funds_div:
        return funds_div  # Already in new format — nothing to do

    # Determine cash for "Total funds available"
    m_after = _FUNDS_AFTER_RE.search(funds_div)
    m_remaining = _FUNDS_REMAINING_RE.search(funds_div)
    cash_str = (m_after or m_remaining)
    cash_str = cash_str.group(1) if cash_str else "0.00"

    # Determine "Total gain/loss" from Realised P&L (already converted above)
    m_pnl = _REALISED_PNL_RE.search(funds_div)
    if m_pnl:
        pnl_color = m_pnl.group(1)
        pnl_amount = m_pnl.group(2)
    else:
        pnl_color = "#0a7c4e"   # green — no sells → no realised loss
        pnl_amount = "+$0.00"

    hist_note = (
        "<span style='font-size:10px;color:#888888'>"
        " (historical, open positions excluded)</span>"
    )
    summary = (
        f"<li><b>Total funds available</b>: ${cash_str}{hist_note}</li>"
        f"<li><b>Total gain/loss</b>: "
        f"<span style='color:{pnl_color};font-weight:bold'>{pnl_amount}</span></li>"
    )
    return funds_div.replace("</ul></div>", summary + "</ul></div>", 1)


def _transform_funds_state(block: str) -> str:
    """Apply all Funds State migrations to a single day block."""
    start = block.find(_FUNDS_DIV_OPEN)
    if start == -1:
        return block  # No Funds State in this block (very old format)

    end_marker = "</ul></div>"
    end_pos = block.find(end_marker, start)
    if end_pos == -1:
        return block  # Malformed — leave untouched
    end_pos += len(end_marker)

    funds_div = block[start:end_pos]
    funds_div = _apply_sold_label_fix(funds_div)
    funds_div = _inject_totals_if_missing(funds_div)
    return block[:start] + funds_div + block[end_pos:]


def _ensure_day_end(block: str) -> str:
    """
    Strip any embedded doc_close fragments and ensure the block ends with
    the <!-- MONITOR_DAY_END --> marker.
    """
    block = _strip_doc_close(block)
    if not block.endswith(_DAY_END):
        block += _DAY_END
    return block


# ── block extraction and assembly ────────────────────────────────────────────

def _split_into_blocks(content: str) -> Tuple[str, List[str]]:
    """
    Split the HTML into (preamble, [day_block, ...]).

    Each Position Monitor day block starts with _spacer(8) immediately before
    the dark Position Monitor header banner.  The preamble is everything that
    precedes the first such block (the pipeline report section).
    """
    starts: List[int] = []
    idx = 0
    while True:
        pos = content.find(_BLOCK_BOUNDARY, idx)
        if pos == -1:
            break
        starts.append(pos)
        idx = pos + 1

    if not starts:
        return content, []

    preamble = content[: starts[0]]
    blocks = [
        content[starts[i]: (starts[i + 1] if i + 1 < len(starts) else len(content))]
        for i in range(len(starts))
    ]
    return preamble, blocks


def _sort_blocks_reverse_chron(blocks: List[str]) -> List[str]:
    """
    Return blocks sorted newest-first by the YYYYMMDD date in each header.
    If they are already in reverse-chronological order the list is unchanged.
    """
    dates = [_get_block_date(b) for b in blocks]
    if dates == sorted(dates, reverse=True):
        return blocks
    return sorted(blocks, key=_get_block_date, reverse=True)


def _rebuild(preamble: str, blocks: List[str]) -> str:
    """
    Re-assemble the HTML:
      clean_preamble + SECTION_ANCHOR + day_blocks + doc_close
    """
    # Remove any stale SECTION_ANCHOR from the preamble (we re-plant it)
    clean_preamble = preamble.replace(_SECTION_ANCHOR, "").rstrip()
    # Remove a dangling PLACEHOLDER (should not normally be present if blocks
    # exist, but guard against it)
    clean_preamble = clean_preamble.replace(_PLACEHOLDER, "").rstrip()

    block_html = "".join(blocks)
    return clean_preamble + _SECTION_ANCHOR + block_html + _DOC_CLOSE


# ── public entry point ───────────────────────────────────────────────────────

def migrate_report(path: Path) -> int:
    """
    Migrate one HTML report file in-place.

    Returns the number of Position Monitor day blocks that were processed
    (0 if the file had nothing to migrate).
    """
    if not path.exists():
        print(f"[migrate] File not found: {path}")
        return 0

    content = path.read_text(encoding="utf-8")

    if _POSMONI_TITLE not in content:
        print(
            f"[migrate] {path.name}: no Position Monitor sections found"
            " — nothing to migrate."
        )
        return 0

    preamble, blocks = _split_into_blocks(content)

    if not blocks:
        print(f"[migrate] {path.name}: no day blocks detected — nothing to migrate.")
        return 0

    # 1. Reverse-chronological order
    blocks = _sort_blocks_reverse_chron(blocks)

    # 2. Transform each block's Funds State labels / totals
    blocks = [_transform_funds_state(b) for b in blocks]

    # 3. Ensure each block ends with MONITOR_DAY_END
    blocks = [_ensure_day_end(b) for b in blocks]

    # 4. Rebuild and write
    new_content = _rebuild(preamble, blocks)
    path.write_text(new_content, encoding="utf-8")

    n = len(blocks)
    print(f"[migrate] {path.name}: migrated {n} day block(s) — done.")
    return n


# ── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    if len(sys.argv) > 1:
        target = Path(sys.argv[1])
    else:
        # Default: position monitor report next to this script
        here = Path(__file__).parent
        target = here / "out" / "position_monitor_report.html"

    migrate_report(target)


if __name__ == "__main__":
    main()
